const KEY='aba-focused-exam-github-v1';let modules=[],active=null,tick=null;
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let sessions={};try{sessions=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{};
const save=()=>localStorage.setItem(KEY,JSON.stringify(sessions));
const same=(a,b)=>a.length===b.length&&[...a].sort().every((x,i)=>x===[...b].sort()[i]);
const session=()=>sessions[active.id];
function home(){active=null;clearInterval(tick);const total=modules.reduce((n,m)=>n+m.questions.length,0);$('#app').innerHTML=`<header class="header"><div class="brand"><span class="mark">A</span>ABA Focused Exam</div><span class="badge">Self-paced practice</span></header><section class="hero"><p class="eyebrow">Focused exam dashboard</p><h1>Choose a module.<br>Test what you know.</h1><p>Select your answer, review it, then press Confirm Answer. Your progress is saved on this device.</p><div class="stats"><div><strong>${modules.length}</strong><span>modules</span></div><div><strong>${total}</strong><span>questions</span></div><div><strong>60</strong><span>minutes each</span></div></div></section><main class="modules"><p class="eyebrow">Question bank</p><h2>Select a module</h2><div class="grid">${modules.map((m,i)=>{let s=sessions[m.id],done=s?Object.values(s.answers).filter(a=>a.confirmed).length:0,score=s?m.questions.filter(q=>s.answers[q.number]?.confirmed&&same(s.answers[q.number].selected,q.correct)).length:0;return `<article class="card"><span class="code">${esc(m.code)}</span><h3>${esc(m.title)}</h3><div class="meta">${m.questions.length} questions · 60 minutes${s?.completedAt?` · Score ${score}/${m.questions.length}`:''}</div><div class="progress"><span style="width:${done/m.questions.length*100}%"></span></div><button class="start" data-open="${m.id}">${s?.completedAt?'Review results':s?'Continue module':'Start module'}</button></article>`}).join('')}</div></main>`;document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>open(b.dataset.open))}
function open(id){active=modules.find(m=>m.id===id);if(!sessions[id])sessions[id]={answers:{},current:0,startedAt:Date.now()};save();if(session().completedAt)results();else{render();clock();clearInterval(tick);tick=setInterval(clock,1000)}}
function clock(){if(!active)return;let left=Math.max(0,active.durationMinutes*60-Math.floor((Date.now()-session().startedAt)/1000)),el=$('#timer'),finishButton=$('#finish');if(el)el.textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;if(finishButton)finishButton.disabled=Object.values(session().answers).filter(x=>x.confirmed).length<active.questions.length;if(!left&&!session().completedAt){session().completedAt=Date.now();session().timedOut=true;save();results()}}
function render(){let s=session(),q=active.questions[s.current],a=s.answers[q.number]||{selected:[],confirmed:false};$('#app').innerHTML=`<header class="header exam-head"><button class="secondary" id="back">← Modules</button><strong>${esc(active.code)}</strong><span class="timer" id="timer">60:00</span></header><div class="layout"><aside class="side"><p class="code">${esc(active.code)}</p><h2>${esc(active.title)}</h2><p>${Object.values(s.answers).filter(x=>x.confirmed).length} of ${active.questions.length} confirmed</p><div class="nav">${active.questions.map((x,i)=>`<button disabled class="${i===s.current?'current':''} ${s.answers[x.number]?.confirmed?'done':''}">${i+1}</button>`).join('')}</div><button class="secondary finish" id="restart">Restart module</button><button class="primary finish" id="finish">Finish module</button></aside><main class="main"><section class="qcard"><div class="qtop"><span>Question ${s.current+1} of ${active.questions.length}</span>${q.multiple?'<span>Select all that apply</span>':''}</div><h1>${esc(q.prompt)}</h1><div class="choices">${q.choices.map(c=>{let selected=a.selected.includes(c.letter),cl=selected?'selected':'',mark='';if(a.confirmed&&q.correct.includes(c.letter)){cl='correct';mark=' ✓'}else if(a.confirmed&&selected){cl='wrong';mark=' ✕'}return `<button class="choice ${cl}" data-choice="${c.letter}" ${a.confirmed?'disabled':''}><span class="letter">${c.letter}${mark}</span><span>${esc(c.text)}</span></button>`}).join('')}</div><div class="confirm"><button class="primary" id="confirm" ${!a.selected.length||a.confirmed?'disabled':''}>Confirm Answer</button></div>${a.confirmed?`<div class="feedback ${same(a.selected,q.correct)?'good':'bad'}"><strong>${same(a.selected,q.correct)?'Correct!':'Not quite.'}</strong><p>Correct answer: ${q.correct.join(', ')}</p><p>${esc(q.explanation)}</p></div>`:''}<div class="actions"><button class="secondary" id="prev" ${s.current===0?'disabled':''}>Previous</button><button class="primary" id="next" ${!a.confirmed||s.current===active.questions.length-1?'disabled':''}>Next</button></div></section></main></div>`;$('#back').onclick=home;$('#restart').onclick=restartModule;$('#finish').onclick=finish;$('#prev').onclick=()=>go(s.current-1);$('#next').onclick=()=>go(s.current+1);document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>choose(b.dataset.choice));$('#confirm').onclick=confirmAnswer;clock()}
function choose(l){let s=session(),q=active.questions[s.current],a=s.answers[q.number]||{selected:[],confirmed:false};a.selected=q.multiple?(a.selected.includes(l)?a.selected.filter(x=>x!==l):[...a.selected,l]):[l];s.answers[q.number]=a;save();render()}
function confirmAnswer(){let s=session(),q=active.questions[s.current];if(s.answers[q.number]?.selected.length){s.answers[q.number].confirmed=true;save();render()}}
function go(i){session().current=i;save();render();scrollTo(0,0)}
function restartModule(){if(!window.confirm('Restart this module? All answers and the timer will reset.'))return;sessions[active.id]={answers:{},current:0,startedAt:Date.now()};save();render();clearInterval(tick);tick=setInterval(clock,1000)}
function finish(){if(Object.values(session().answers).filter(x=>x.confirmed).length<active.questions.length)return;if(!window.confirm('Finish this module and view your score?'))return;session().completedAt=Date.now();save();results()}
function results(){clearInterval(tick);let s=session(),score=active.questions.filter(q=>s.answers[q.number]?.confirmed&&same(s.answers[q.number].selected,q.correct)).length;$('#app').innerHTML=`<header class="header"><div class="brand"><span class="mark">A</span>ABA Focused Exam</div></header><main class="result"><p class="eyebrow">Module complete</p><h1>${esc(active.code)}</h1><p>${esc(active.title)}</p><div class="score">${score}/${active.questions.length}</div><p>${s.timedOut?'Time expired. ':''}You can review your answers or restart with a fresh 60-minute timer.</p><div class="actions"><button class="secondary" id="modules">All modules</button><button class="secondary" id="review">Review</button><button class="primary" id="retry">Retry</button></div></main>`;$('#modules').onclick=home;$('#review').onclick=()=>{session().current=0;render()};$('#retry').onclick=()=>{sessions[active.id]={answers:{},current:0,startedAt:Date.now()};save();render();clearInterval(tick);tick=setInterval(clock,1000)}}
fetch('quiz-data.json').then(r=>{if(!r.ok)throw Error('Quiz data could not be loaded.');return r.json()}).then(d=>{modules=d;home()}).catch(e=>{$('#app').innerHTML=`<p class="loading">${esc(e.message)}</p>`});
